apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kaknas-vue
  namespace: default
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: kaknas-vue
    spec:
      containers:
      - name: kaknas-vue
        image: eu.gcr.io/cognitedata/kaknas-vue:25
        ports:
        - name: kaknas-vue
          containerPort: 8080
        resources:
          requests:
            cpu: "500m"
            memory: "500Mi"
          limits:
            cpu: "500m"
            memory: "500Mi"
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: kaknas-vue
#   namespace: default
#   labels:
#     app: kaknas-vue
# spec:
#   ports:
#     - port: 80
#       targetPort: 8080
#       protocol: TCP
#       name: http
#   selector:
#     app: kaknas-vue
